// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcX4M0dqa-P2drcPqgc3rLqiGiaDURo18',
    appId: '1:1025553075434:web:92016e51fa67c72c475b93',
    messagingSenderId: '1025553075434',
    projectId: 'food-recipes-e34be',
    authDomain: 'food-recipes-e34be.firebaseapp.com',
    storageBucket: 'food-recipes-e34be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKR2aVg1UNEUVGNpHYauLVpNrMmSn_fTQ',
    appId: '1:1025553075434:android:d8c19ca548c082a1475b93',
    messagingSenderId: '1025553075434',
    projectId: 'food-recipes-e34be',
    storageBucket: 'food-recipes-e34be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGS--Plw3VTqQ4Q9J-9WW2jI68vhEKYFU',
    appId: '1:1025553075434:ios:300b46bfb63c4a22475b93',
    messagingSenderId: '1025553075434',
    projectId: 'food-recipes-e34be',
    storageBucket: 'food-recipes-e34be.appspot.com',
    iosClientId: '1025553075434-a51k4cnlpq99epvvp2dqhp3tcfomaerf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBtvn',
  );
}
